#!/usr/bin/env python3
#
# Copyright (C) 2019 Intel Corporation.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
import argparse
import os
from pathlib import Path
import re
import shlex
import subprocess
import sys

"""
This is a tool to convert addresses, which are from a call-stack dump generated by iwasm, into line info for a wasm file.

When a wasm file is compiled with debug info (-g), it is possible to transfer the address to line info.

For example, there is a call-stack dump:

```
#00: 0x0a04 - $f18
#01: 0x08e4 - $f11
#02: 0x096f - $f12
#03: 0x01aa - _start
```

- store the call-stack dump into a file, e.g. call_stack.txt
- run the following command:
  ```
  $ python3 addr2line.py --wasi-sdk <wasi-sdk> --wabt <wabt> --wasm-file <wasm file> call_stack.txt
  ```

The script handles two workflows:
- Same-binary: pass the wasm file that ran (must have DWARF debug info)
- Companion: pass a sibling debug companion (.debug.wasm produced by `wasm-opt -Oz -g`).
  The production binary that ran can be stripped — the companion has identical code
  layout but retains DWARF, so the runtime offsets map correctly.

Inline expansion (DW_TAG_inlined_subroutine) is automatic — no flag needed.

If addresses are not available (iwasm <= 1.3.2 or fast interpreter mode), pass `--no-addr`
to look up by function index/name only.
"""


def locate_sourceMappingURL_section(wasm_objdump: Path, wasm_file: Path) -> bool:
    """Figure out if the wasm file has a sourceMappingURL section."""
    cmd = f"{wasm_objdump} -h {wasm_file}"
    p = subprocess.run(
        shlex.split(cmd),
        check=True,
        capture_output=True,
        text=True,
        universal_newlines=True,
    )
    for line in p.stdout.splitlines():
        if "sourceMappingURL" in line.strip():
            return True
    return False


def get_code_section_start(wasm_objdump: Path, wasm_file: Path) -> int:
    """
    Find the start file offset of the Code section in a wasm file.

    Code section header looks like:
      Code start=0x0000017c end=0x00004382 (size=0x00004206) count: 47
    """
    cmd = f"{wasm_objdump} -h {wasm_file}"
    p = subprocess.run(
        shlex.split(cmd),
        check=True,
        capture_output=True,
        text=True,
        universal_newlines=True,
    )
    for line in p.stdout.splitlines():
        line = line.strip()
        if "Code" in line and "start=" in line:
            m = re.search(r"start=(0x[0-9a-fA-F]+)", line)
            if m:
                return int(m.group(1), 16)
    return -1


def resolve_address(
    llvm_addr2line: Path, wasm_file: Path, dwarf_addr: int
) -> list:
    """
    Resolve a DWARF address to a list of inline frames.

    Runs: llvm-addr2line -e <wasm_file> -f -i 0x<dwarf_addr>

    llvm-addr2line outputs pairs of lines per frame:
        function_name
        file:line[:column]
    With -i, multiple pairs are returned (one per inline depth, innermost first).

    Returns a list of (function_name, file, line, column) tuples.
    Each field is a string; line and column may be "?" if unknown.
    """
    addr_str = f"0x{dwarf_addr:x}"
    cmd = f"{llvm_addr2line} -e {wasm_file} -f -i {addr_str}"
    p = subprocess.run(
        shlex.split(cmd),
        check=False,
        capture_output=True,
        text=True,
        universal_newlines=True,
    )
    output_lines = [line for line in p.stdout.splitlines() if line.strip()]

    frames = []
    for i in range(0, len(output_lines) - 1, 2):
        func_name = output_lines[i].strip()
        location = output_lines[i + 1].strip()

        # Parse "file:line:column" or "file:line" or "??:0"
        m = re.match(r"^(.*):(\d+):(\d+)$", location)
        if m:
            file, line, column = m.group(1), m.group(2), m.group(3)
        else:
            m = re.match(r"^(.*):(\d+)$", location)
            if m:
                file, line, column = m.group(1), m.group(2), "?"
            else:
                file, line, column = location, "?", "?"

        frames.append((func_name, file, line, column))

    return frames


def parse_call_stack_line(line: str) -> tuple:
    """
    New format (WAMR > 1.3.2):
    #00: 0x0a04 - $f18   => (00, 0x0a04, $f18)
    Old format:
    #00 $f18             => (00, _, $f18)
    Text format (-DWAMR_BUILD_LOAD_CUSTOM_SECTION=1 -DWAMR_BUILD_CUSTOM_NAME_SECTION=1):
    #02: 0x0200 - a      => (02, 0x0200, a)
    _start (always):
    #05: 0x011f - _start => (05, 0x011f, _start)
    """
    # New format and Text format and _start
    PATTERN = r"#([0-9]+): 0x([0-9a-f]+) - (\S+)"
    m = re.match(PATTERN, line)
    if m is not None:
        return m.groups()

    # Old format
    PATTERN = r"#([0-9]+) (\S+)"
    m = re.match(PATTERN, line)
    if m is not None:
        return (m.groups()[0], None, m.groups()[1])

    return None


def parse_module_functions(wasm_objdump: Path, wasm_file: Path) -> dict:
    """Map function index to name from wasm-objdump output."""
    function_index_to_name = {}

    cmd = f"{wasm_objdump} -x {wasm_file} --section=function"
    p = subprocess.run(
        shlex.split(cmd),
        check=True,
        capture_output=True,
        text=True,
        universal_newlines=True,
    )
    for line in p.stdout.splitlines():
        if "func[" not in line:
            continue
        PATTERN = r".*func\[([0-9]+)\].*<(.*)>"
        m = re.match(PATTERN, line)
        if m is None:
            continue
        index = m.groups()[0]
        name = m.groups()[1]
        function_index_to_name[index] = name

    return function_index_to_name


def get_line_info_from_function_name_dwarf(
    dwarf_dump: Path, wasm_file: Path, function_name: str
) -> tuple:
    """
    Used by --no-addr mode. llvm-addr2line doesn't support name lookup,
    so we keep this small helper using llvm-dwarfdump.

    Returns (function_name, file, line).
    """
    cmd = f"{dwarf_dump} --name={function_name} {wasm_file}"
    p = subprocess.run(
        shlex.split(cmd),
        check=False,
        capture_output=True,
        text=True,
        universal_newlines=True,
    )

    found_name, found_file, found_line = "<unknown>", "unknown", "?"
    for line in p.stdout.splitlines():
        line = line.strip()

        m = re.match(r'DW_AT_name\s+\("(.+)"\)', line)
        if m:
            found_name = m.group(1)

        m = re.match(r'DW_AT_decl_file\s+\("(.+)"\)', line)
        if m:
            found_file = m.group(1)

        m = re.match(r"DW_AT_decl_line\s+\((\d+)\)", line)
        if m:
            found_line = m.group(1)

    return (found_name, found_file, found_line)


def get_line_info_from_function_addr_sourcemapping(
    emsymbolizer: Path, wasm_file: Path, offset: int
) -> tuple:
    """
    Find the location info of a given offset in a wasm file compiled with emcc.

    {emsymbolizer} {wasm_file} {offset}

    Output is two lines:
      ??
      relative path to source:line:column
    """
    debug_info_source = wasm_file.with_name(f"{wasm_file.name}.map")
    cmd = f"{emsymbolizer} -t code -f {debug_info_source} {wasm_file} {offset}"
    p = subprocess.run(
        shlex.split(cmd),
        check=False,
        capture_output=True,
        text=True,
        universal_newlines=True,
        cwd=Path.cwd(),
    )

    function_name, function_file = "<unknown>", "unknown"
    function_line, function_column = "?", "?"

    for line in p.stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        m = re.match(r"(.*):(\d+):(\d+)", line)
        if m:
            function_file, function_line, function_column = m.groups()
            continue
        if "??" != line:
            function_name = line

    return (function_name, function_file, function_line, function_column)


def demangle(cxxfilt: Path, function_name: str) -> str:
    cmd = f"{cxxfilt} -n {function_name}"
    p = subprocess.run(
        shlex.split(cmd),
        check=True,
        capture_output=True,
        text=True,
        universal_newlines=True,
    )
    return p.stdout.strip()


def print_frames(index_str: str, frames: list, cxxfilt: Path) -> None:
    """
    Print resolved frames with consistent indentation.

    Single frame:
        0: c
                at trap.c:4:5

    Multiple frames (inlines):
        0: do_bad_access
                at oob_access.c:11:5
           trigger_oob
                at oob_main.c:17:5
           app_main
                at oob_main.c:23:5

    The first frame uses "<index>:" prefix; subsequent frames use the same
    width of leading spaces for vertical alignment.
    """
    prefix = f"{index_str}:"
    indent = " " * len(prefix)

    for i, (func_name, file, line, column) in enumerate(frames):
        demangled = demangle(cxxfilt, func_name) if func_name != "??" else "<unknown>"
        leading = prefix if i == 0 else indent
        print(f"{leading} {demangled}")
        if column != "?":
            print(f"\tat {file}:{line}:{column}")
        else:
            print(f"\tat {file}:{line}")


def main():
    parser = argparse.ArgumentParser(description="addr2line for wasm")
    parser.add_argument("--wasi-sdk", type=Path, required=True, help="path to wasi-sdk")
    parser.add_argument("--wabt", type=Path, required=True, help="path to wabt")
    parser.add_argument("--wasm-file", type=Path, required=True, help="path to wasm file (must have DWARF)")
    parser.add_argument("call_stack_file", type=Path, help="path to a call stack file")
    parser.add_argument(
        "--no-addr",
        action="store_true",
        help="use call stack without addresses or from fast interpreter mode",
    )
    parser.add_argument("--emsdk", type=Path, help="path to emsdk")
    args = parser.parse_args()

    wasm_objdump = args.wabt.joinpath("bin/wasm-objdump")
    assert wasm_objdump.exists(), f"wasm-objdump not found at {wasm_objdump}"

    llvm_addr2line = args.wasi_sdk.joinpath("bin/llvm-addr2line")
    assert llvm_addr2line.exists(), f"llvm-addr2line not found at {llvm_addr2line}"

    llvm_dwarf_dump = args.wasi_sdk.joinpath("bin/llvm-dwarfdump")
    assert llvm_dwarf_dump.exists(), f"llvm-dwarfdump not found at {llvm_dwarf_dump}"

    llvm_cxxfilt = args.wasi_sdk.joinpath("bin/llvm-cxxfilt")
    assert llvm_cxxfilt.exists(), f"llvm-cxxfilt not found at {llvm_cxxfilt}"

    emcc_production = locate_sourceMappingURL_section(wasm_objdump, args.wasm_file)
    if emcc_production:
        if args.emsdk is None:
            print("Please provide the path to emsdk via --emsdk")
            return -1
        emsymbolizer = args.emsdk.joinpath("upstream/emscripten/emsymbolizer")
        assert emsymbolizer.exists()

    code_section_start = get_code_section_start(wasm_objdump, args.wasm_file)
    if code_section_start == -1:
        print("Could not find Code section in wasm file", file=sys.stderr)
        return -1

    function_index_to_name = parse_module_functions(wasm_objdump, args.wasm_file)

    assert args.call_stack_file.exists(), f"call stack file not found: {args.call_stack_file}"
    with open(args.call_stack_file, "rt", encoding="ascii") as f:
        for i, line in enumerate(f):
            line = line.strip()
            if not line:
                continue

            splitted = parse_call_stack_line(line)
            if splitted is None:
                print(f"{line}")
                continue

            _, offset, index = splitted
            index_str = str(i)

            if args.no_addr:
                # FIXME: w/ emcc production
                if not index.startswith("$f"):  # E.g. _start or Text format
                    print(f"{index_str}: {index}")
                    continue
                func_idx = index[2:]

                if func_idx not in function_index_to_name:
                    print(f"{index_str}: {line}")
                    continue

                if not emcc_production:
                    _, function_file, function_line = (
                        get_line_info_from_function_name_dwarf(
                            llvm_dwarf_dump, args.wasm_file,
                            function_index_to_name[func_idx],
                        )
                    )
                else:
                    function_file, function_line = "unknown", "?"

                function_name = demangle(llvm_cxxfilt, function_index_to_name[func_idx])
                print(f"{index_str}: {function_name}")
                print(f"\tat {function_file}:{function_line}")
                continue

            # Address-based lookup
            offset_int = int(offset, 16)

            # WAMR reports offset 0 when frame_ip wasn't captured (e.g., trap
            # at function entry, or top frame of an iwasm -f invocation where
            # ip wasn't sync'd before the trap). Fall back to function-name
            # lookup for the function header instead of asserting.
            if offset_int == 0 or offset_int <= code_section_start:
                if not emcc_production:
                    # Resolve function name from index ($fN) or use the name directly
                    if index.startswith("$f"):
                        func_idx = index[2:]
                        func_name = function_index_to_name.get(func_idx, index)
                    else:
                        func_name = index
                    _, function_file, function_line = (
                        get_line_info_from_function_name_dwarf(
                            llvm_dwarf_dump, args.wasm_file, func_name
                        )
                    )
                    print(f"{index_str}: {demangle(llvm_cxxfilt, func_name)}")
                    print(f"\tat {function_file}:{function_line}  "
                          f"(offset=0 — function entry, no inline info)")
                    continue
                # emcc path: just print raw
                print(f"{index_str}: {index}")
                print(f"\tat unknown:?:?  (offset=0 — frame_ip not captured)")
                continue

            # Apply -1: WAMR's frame_ip has always advanced past the trapping opcode
            # before the trap handler runs (FETCH_OPCODE_AND_DISPATCH increments ip
            # before dispatching, plus LEB reads inside store handlers).
            dwarf_addr = offset_int - code_section_start - 1

            if emcc_production:
                # Source-map path doesn't support inline expansion; emit single frame.
                func_name, file, line, column = (
                    get_line_info_from_function_addr_sourcemapping(
                        emsymbolizer, args.wasm_file, dwarf_addr
                    )
                )
                # Fall back to function index name if unresolved
                if func_name == "<unknown>" and index.startswith("$f"):
                    func_name = function_index_to_name.get(index[2:], index)
                func_name = demangle(llvm_cxxfilt, func_name)
                print(f"{index_str}: {func_name}")
                print(f"\tat {file}:{line}:{column}")
                continue

            frames = resolve_address(llvm_addr2line, args.wasm_file, dwarf_addr)

            if not frames:
                # Fall back to function index name
                if index.startswith("$f"):
                    func_name = function_index_to_name.get(index[2:], index)
                else:
                    func_name = index
                print(f"{index_str}: {demangle(llvm_cxxfilt, func_name)}")
                print(f"\tat unknown:?:?")
                continue

            # If outermost frame is "??", replace with function index name
            if frames[-1][0] == "??" and index.startswith("$f"):
                fallback = function_index_to_name.get(index[2:], index)
                frames[-1] = (fallback,) + frames[-1][1:]

            print_frames(index_str, frames, llvm_cxxfilt)

    return 0


if __name__ == "__main__":
    sys.exit(main())
